export * from './ping.controller';
export * from './empleado.controller';
export * from './jefe.controller';
export * from './departamento.controller';
export * from './permiso-hora.controller';
export * from './permiso-dia.controller';
export * from './marcar.controller';
export * from './vacaciones.controller';
export * from './turnos.controller';
